# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-14 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posts_text', models.CharField(max_length=255)),
                ('posts_pub_date', models.DateTimeField(verbose_name='date posted')),
                ('posts_author', models.CharField(max_length=100)),
                ('posts_title', models.CharField(max_length=100)),
            ],
        ),
    ]
